version: '3.8'
services:
  ruby:
    build: .
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    command: sh -c "rm -f tmp/pids/server.pid && 
                    if [ ! -f Gemfile ]; then 
                      gem install bundler rails && 
                      rails new .; 
                    fi && 
                    rails server -b 0.0.0.0"
    stdin_open: true
    tty: true
